apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-simple
  namespace: logging
spec:
  fluentbit:
    image:
      repository: rancher/mirrored-fluent-fluent-bit
      tag: 1.6.10
  fluentd:
    configReloaderImage:
      repository: rancher/mirrored-jimmidyson-configmap-reload
      tag: v0.4.0
    disablePvc: true
    image:
      repository: rancher/mirrored-banzaicloud-fluentd
      tag: v1.11.5-alpine-12
  controlNamespace: logging

