apiVersion: v1
kind: Service
metadata:
  name: {{ include "log-generator.fullname" . }}-metrics
  labels:
{{ include "log-generator.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.metricsAddr }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "log-generator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
