apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flask-demo-flow
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: json
  match:
    - select:
        labels:
          app.kubernetes.io/name: flask-demo
  localOutputRefs:
    - es-output
